#[theme]
#theme = "solarized-dark"

[icons]
icons = "material-nf"

[[block]]
block = "net"
device = "wlan0"
format = " W: ($ssid at $signal_strength) $ip "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "nvidia_gpu"
interval = 4
format = " $memory.eng(w:3,prefix_space:true) "


#[[block]]
#block = "memory"
#format = " $mem_used.eng(p:Gi,w:3,hide_unit:true,hide_prefix:true) GB "
#interval = 5

[[block]]
block="custom"
command="sh ~/.config/i3blocks/memory_htop.sh"
format=" $text "
interval=1

[[block]]
block = "battery"
interval = 10
format = "$percentage "

[[block]]
block = "time"
interval = 10
format =" $timestamp.datetime(f:'%d/%m %R') "

[[block]]
block ="time"
interval = 10
format =" $timestamp.datetime(f:'%d/%m %R') "
timezone="Asia/Kolkata"


[theme.overrides]
idle_bg = "#000000"
idle_fg = "#FF0000"
info_bg = "#000000"
info_fg = "#FF0000"
good_bg = "#000000"
good_fg = "#FF0000"
warning_bg = "#000000"
warning_fg = "#FF0000"
critical_bg = "#000000"
critical_fg = "#FF0000"
separator = "|"
    

