[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
